variable "vpc_cidr_block" {}
variable "subnet_cidr_block" {}
variable "avail_zone" {}
variable "env_prefix" {}
variable "my_ip" {}
variable "route_table_cidr_block" {}
variable "image_name" {}
variable "instance_type" {}
variable "public_key_location" {}
variable "ssh_private_key" {}
